### ISSUE TITLE
Segmentation fault when providing 1 argument.

### ISSUE THREAD

**Issue by zebp** [sam-barr/png-rs#2]
This check [here](https://github.com/sam-barr/png-rs/blob/master/src/main.rs#L41) tries to ensure that the user provided two arguments but checks if the length of `args` is 2, but the first argument is always the path to the executable binary.  Changing the check to ensure that the length of `args` is less than 3 should fix this.

[Screenshot](https://zeb.website/SpotlessThoughtfulCry.png)

**Comment by zebp** [comment]
Nevermind, I am an idiot.

**Comment by ss7m** [comment]
No worries, I appreciate you taking the time to look over my code
